# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 265d42b71cda5396bc232a17f53c46d751aadde13b930f2cfd42dcc5eeefa6727837a04bbe2ccf6a6137e063cb84a9a421feb6aefef3a80164a73af74f44bd0d

test:
  secret_key_base: 443b04800c2f5bba21f558fe2189e6efaec711239829dc9b48e5e556f35e7d9323c43c062c3230d4b25962ad3d2c581ccf93b8775c603408a3ec99070216c93c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
